name: sysmail_configure_sp
fullyQualifiedName: MSSQL_TEST.msdb.dbo.sysmail_configure_sp
storedProcedureCode:
  language: SQL
  code: "\r\nCREATE   PROCEDURE dbo.sysmail_configure_sp\r\n   @parameter_name nvarchar(256),\r\
    \n   @parameter_value nvarchar(256),\r\n   @description nvarchar(256) = NULL\r\
    \nAS\r\n   SET NOCOUNT ON\r\n   \r\n   IF (@description IS NOT NULL)\r\n     \
    \ UPDATE msdb.dbo.sysmail_configuration\r\n      SET paramvalue=@parameter_value,\
    \ description=@description\r\n      WHERE paramname=@parameter_name\r\n   ELSE\r\
    \n      UPDATE msdb.dbo.sysmail_configuration\r\n      SET paramvalue=@parameter_value\r\
    \n      WHERE paramname=@parameter_name\r\n\r\n   RETURN(0)\r\n"
dataProducts: []
databaseSchema:
  id: 57c2f396-9b05-4e00-9903-62b0219fbc25
  type: databaseSchema
  name: dbo
  fullyQualifiedName: MSSQL_TEST.msdb.dbo
  displayName: dbo
  deleted: false
database:
  id: af8db866-dbb4-4bd5-a2ea-22202fbc71ef
  type: database
  name: msdb
  fullyQualifiedName: MSSQL_TEST.msdb
  displayName: msdb
  deleted: false
service:
  id: 1ef4c8da-1280-42c0-8b83-142c3a019de7
  type: databaseService
  name: MSSQL_TEST
  fullyQualifiedName: MSSQL_TEST
  description: ""
  displayName: MSSQL_TEST
  deleted: false
serviceType: Mssql
owners: []
tags: []
domains: []
sourceHash: 9a4952793dd518c40a8aebcf4818e5a1
processedLineage: false
entityStatus: Approved
