name: openmetadata_settings
fullyQualifiedName: mysql-dq-testing.default.openmetadata.openmetadata_settings
tableType: Regular
columns:
  - name: id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: mediumint
    fullyQualifiedName: mysql-dq-testing.default.openmetadata.openmetadata_settings.id
    tags: []
    children: []
    customMetrics: []
  - name: configType
    dataType: VARCHAR
    dataLength: 36
    dataTypeDisplay: varchar(36)
    fullyQualifiedName: mysql-dq-testing.default.openmetadata.openmetadata_settings.configType
    tags: []
    children: []
    customMetrics: []
  - name: json
    dataType: JSON
    dataLength: 1
    dataTypeDisplay: json
    fullyQualifiedName: mysql-dq-testing.default.openmetadata.openmetadata_settings.json
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints:
  - constraintType: PRIMARY_KEY
    columns:
      - configType
      - id
owners: []
databaseSchema:
  id: d14daac9-6fbe-4ad0-bc35-761e5ccdf8aa
  type: databaseSchema
  name: openmetadata
  fullyQualifiedName: mysql-dq-testing.default.openmetadata
  displayName: openmetadata
  deleted: false
database:
  id: 2dc91e0a-9aa2-4330-aada-7fc024ee6025
  type: database
  name: default
  fullyQualifiedName: mysql-dq-testing.default
  displayName: default
  deleted: false
service:
  id: 1941656b-2a1e-4b70-bca5-02d5aa036a86
  type: databaseService
  name: mysql-dq-testing
  fullyQualifiedName: mysql-dq-testing
  description: ""
  displayName: mysql-dq-testing
  deleted: false
serviceType: Mysql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 9fbae884f956522cb4a60c22784a762f
processedLineage: false
entityStatus: Approved
