name: RDS_EV_CONFIGURATION
fullyQualifiedName: oracle_test.default.rdsadmin.RDS_EV_CONFIGURATION
tableType: Regular
columns:
  - name: event_number
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: "number(10,0)"
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_EV_CONFIGURATION.event_number
    tags: []
    constraint: PRIMARY_KEY
    children: []
    customMetrics: []
  - name: event_type
    dataType: VARCHAR
    dataLength: 10
    dataTypeDisplay: varchar2(10)
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_EV_CONFIGURATION.event_type
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: manually_added
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: varchar2(1)
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_EV_CONFIGURATION.manually_added
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: creation_date
    dataType: DATE
    dataLength: 1
    dataTypeDisplay: date
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_EV_CONFIGURATION.creation_date
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: last_action
    dataType: VARCHAR
    dataLength: 10
    dataTypeDisplay: varchar2(10)
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_EV_CONFIGURATION.last_action
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: last_level
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: "number(10,0)"
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_EV_CONFIGURATION.last_level
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: last_action_date
    dataType: DATE
    dataLength: 1
    dataTypeDisplay: date
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_EV_CONFIGURATION.last_action_date
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: event_comment
    dataType: VARCHAR
    dataLength: 256
    dataTypeDisplay: varchar2(256)
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_EV_CONFIGURATION.event_comment
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 4e5fec0f-68e3-4e71-9986-d123da76d830
  type: databaseSchema
  name: rdsadmin
  fullyQualifiedName: oracle_test.default.rdsadmin
  displayName: rdsadmin
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: f1f4681916aec83c86d6c59e66e8ab4d
processedLineage: false
entityStatus: Approved
