name: RDS_CONFIGURATION
fullyQualifiedName: oracle_test.default.rdsadmin.RDS_CONFIGURATION
tableType: Regular
columns:
  - name: name
    dataType: VARCHAR
    dataLength: 30
    dataTypeDisplay: varchar2(30)
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_CONFIGURATION.name
    tags: []
    constraint: PRIMARY_KEY
    children: []
    customMetrics: []
  - name: value
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_CONFIGURATION.value
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: description
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.rdsadmin.RDS_CONFIGURATION.description
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 4e5fec0f-68e3-4e71-9986-d123da76d830
  type: databaseSchema
  name: rdsadmin
  fullyQualifiedName: oracle_test.default.rdsadmin
  displayName: rdsadmin
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 209528cb935f65f5628ef34c88f3c793
processedLineage: false
entityStatus: Approved
