name: INNODB_FT_CONFIG
fullyQualifiedName: Gyo local test mysql 20240324.dev.information_schema.INNODB_FT_CONFIG
tableType: View
columns:
  - name: KEY
    dataType: VARCHAR
    dataLength: 193
    dataTypeDisplay: varchar(193)
    fullyQualifiedName: Gyo local test mysql 20240324.dev.information_schema.INNODB_FT_CONFIG.KEY
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: VALUE
    dataType: VARCHAR
    dataLength: 193
    dataTypeDisplay: varchar(193)
    fullyQualifiedName: Gyo local test mysql 20240324.dev.information_schema.INNODB_FT_CONFIG.VALUE
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: b489d438-84fc-4a8e-bd10-306565d429b2
  type: databaseSchema
  name: information_schema
  fullyQualifiedName: Gyo local test mysql 20240324.dev.information_schema
  displayName: information_schema
  deleted: false
database:
  id: 10d003d9-752e-4fd1-b689-f672d928d570
  type: database
  name: dev
  fullyQualifiedName: Gyo local test mysql 20240324.dev
  displayName: dev
  deleted: false
service:
  id: dd58523e-5854-4abb-a406-2ebc62218821
  type: databaseService
  name: Gyo local test mysql 20240324
  fullyQualifiedName: Gyo local test mysql 20240324
  description: ""
  displayName: Gyo local test mysql 20240324
  deleted: false
serviceType: Mysql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 3329ba54ef8f0726c855a59fa98ca35e
processedLineage: false
entityStatus: Approved
