name: DBMS_FEATURE_LABEL_SECURITY
fullyQualifiedName: oracle_test.default.sys.DBMS_FEATURE_LABEL_SECURITY
storedProcedureCode:
  language: SQL
  code: |-
    begin
    PROCEDURE dbms_feature_label_security
         ( feature_boolean  OUT NUMBER,
           aux_count        OUT NUMBER,
           feature_info     OUT CLOB)
    AS
      -- execute immediate as lbacsys is not installed yet
      execute immediate 'begin lbacsys.feature_usage(:1,:2,:3); end;'
                         USING OUT feature_boolean,
                               OUT aux_count,
                               OUT feature_info;

      EXCEPTION WHEN OTHERS THEN
        null;

    end dbms_feature_label_security;
dataProducts: []
storedProcedureType: StoredProcedure
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
owners: []
tags: []
domains: []
sourceHash: 77896771d9228c3b1aee973077a96832
processedLineage: false
entityStatus: Approved
