name: server_settings
fullyQualifiedName: test_clickhouse.default.system.server_settings
description: "Contains a list of all server-wide settings (which are effective only\
  \ on server startup and usually cannot be modified at runtime), their current and\
  \ default values along with descriptions."
tableType: Regular
columns:
  - name: name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Server setting name.
    fullyQualifiedName: test_clickhouse.default.system.server_settings.name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: value
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Server setting value.
    fullyQualifiedName: test_clickhouse.default.system.server_settings.value
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: default
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Server setting default value.
    fullyQualifiedName: test_clickhouse.default.system.server_settings.default
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: changed
    dataType: SMALLINT
    dataLength: 1
    dataTypeDisplay: uint8
    description: Shows whether a setting was specified in config.xml
    fullyQualifiedName: test_clickhouse.default.system.server_settings.changed
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: description
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Short server setting description.
    fullyQualifiedName: test_clickhouse.default.system.server_settings.description
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: type
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Server setting value type.
    fullyQualifiedName: test_clickhouse.default.system.server_settings.type
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: changeable_without_restart
    dataType: ENUM
    dataLength: 1
    dataTypeDisplay: "enum8<'no' = 0, 'increaseonly' = 1, 'decreaseonly' = 2, 'yes'\
      \ = 3>"
    description: Shows whether a setting can be changed at runtime.
    fullyQualifiedName: test_clickhouse.default.system.server_settings.changeable_without_restart
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: is_obsolete
    dataType: SMALLINT
    dataLength: 1
    dataTypeDisplay: uint8
    description: Shows whether a setting is obsolete.
    fullyQualifiedName: test_clickhouse.default.system.server_settings.is_obsolete
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 8a7299bd-4233-40a1-9e70-dc760e5e6b42
  type: databaseSchema
  name: system
  fullyQualifiedName: test_clickhouse.default.system
  displayName: system
  deleted: false
database:
  id: 892667da-43ed-425c-94ad-24a4cc252df4
  type: database
  name: default
  fullyQualifiedName: test_clickhouse.default
  displayName: default
  deleted: false
service:
  id: b468f00e-0925-45e5-a89d-c038e1a5e79f
  type: databaseService
  name: test_clickhouse
  fullyQualifiedName: test_clickhouse
  description: ""
  displayName: test_clickhouse
  deleted: false
serviceType: Clickhouse
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: lifeCycle
      newValue: "{\"accessed\":{\"timestamp\":1768521600000,\"accessedByAProcess\"\
        :\"monitoring-internal\"}}"
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary: {}
domains: []
dataProducts: []
lifeCycle:
  accessed:
    timestamp: 1768521600000
    accessedByAProcess: monitoring-internal
sourceHash: 960434559f65c56fd281d1a04e6736bd
processedLineage: false
entityStatus: Unprocessed
