name: settings_changes
fullyQualifiedName: test_clickhouse.default.system.settings_changes
description: Contains the information about the settings changes through different
  ClickHouse versions. You may make ClickHouse behave like a particular previous version
  by changing the `compatibility` user-level settings.
tableType: Regular
columns:
  - name: type
    dataType: ENUM
    dataLength: 1
    dataTypeDisplay: "enum8<'session' = 0, 'mergetree' = 1>"
    description: "The group of settings (Session, MergeTree...)"
    fullyQualifiedName: test_clickhouse.default.system.settings_changes.type
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: version
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: The ClickHouse server version.
    fullyQualifiedName: test_clickhouse.default.system.settings_changes.version
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: changes
    dataType: ARRAY
    arrayDataType: TUPLE
    dataTypeDisplay: |-
      array<tuple<
      namestring,
      previous_valuestring,
      new_valuestring,
      reasonstring>>
    description: The list of changes in settings which changed the behaviour of ClickHouse.
    fullyQualifiedName: test_clickhouse.default.system.settings_changes.changes
    tags: []
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 8a7299bd-4233-40a1-9e70-dc760e5e6b42
  type: databaseSchema
  name: system
  fullyQualifiedName: test_clickhouse.default.system
  displayName: system
  deleted: false
database:
  id: 892667da-43ed-425c-94ad-24a4cc252df4
  type: database
  name: default
  fullyQualifiedName: test_clickhouse.default
  displayName: default
  deleted: false
service:
  id: b468f00e-0925-45e5-a89d-c038e1a5e79f
  type: databaseService
  name: test_clickhouse
  fullyQualifiedName: test_clickhouse
  description: ""
  displayName: test_clickhouse
  deleted: false
serviceType: Clickhouse
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 7c41eaa04bab8653dafd7f9ced7c365f
processedLineage: false
entityStatus: Unprocessed
