name: SERVICES
fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES
tableType: View
columns:
  - name: SERVICE_CATALOG
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Database that the service belongs to
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.SERVICE_CATALOG
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_SCHEMA
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Schema that the service belongs to
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.SERVICE_SCHEMA
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the service
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.SERVICE_NAME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_OWNER
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the role that owns the service
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.SERVICE_OWNER
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_OWNER_ROLE_TYPE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Type of role that owns the service
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.SERVICE_OWNER_ROLE_TYPE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: COMPUTE_POOL_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the compute pool where the service runs
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.COMPUTE_POOL_NAME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: DNS_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: DNS name associated with the service
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.DNS_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MIN_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Mininum number of active instances for the service
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.MIN_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: MAX_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Maximum number of active instances for the service
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.MAX_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: AUTO_RESUME
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether the service can be automatically resumed
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.AUTO_RESUME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: COMMENT
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Comment for this service
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.COMMENT
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: QUERY_WAREHOUSE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Query warehouse of the service
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.QUERY_WAREHOUSE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CREATED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Creation time of the service
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.CREATED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_ALTERED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Last altered time of the service
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.LAST_ALTERED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_RESUMED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Time when the service was last resumed
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.LAST_RESUMED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IS_JOB
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether this is a Snowpark Container Services Job
    fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA.SERVICES.IS_JOB
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: edd68efa-a871-40fd-8c01-c19d84895707
  type: databaseSchema
  name: INFORMATION_SCHEMA
  fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA.INFORMATION_SCHEMA
  description: Views describing the contents of schemas in this database
  displayName: INFORMATION_SCHEMA
  deleted: false
database:
  id: 7fc7fe92-547f-478e-b870-936ddfc693a3
  type: database
  name: SAMPLE_CUSTOMER_DATA
  fullyQualifiedName: SnowflakeProd.SAMPLE_CUSTOMER_DATA
  description: ""
  displayName: SAMPLE_CUSTOMER_DATA
  deleted: false
service:
  id: 486b5c07-139b-4e9b-b384-0cb7327fb7b9
  type: databaseService
  name: SnowflakeProd
  fullyQualifiedName: SnowflakeProd
  description: ""
  displayName: SnowflakeProd
  deleted: false
serviceType: Snowflake
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
sourceUrl: https://app.snowflake.com/nxxicwj/ax71538/#/data/databases/SAMPLE_CUSTOMER_DATA/schemas/INFORMATION_SCHEMA/view/SERVICES
domains: []
dataProducts: []
sourceHash: 4abdc3997bc2b4f6eb7425aab480f4c0
processedLineage: false
entityStatus: Approved
