name: dba_sql_management_config
fullyQualifiedName: oracle_test.default.sys.dba_sql_management_config
tableType: View
columns:
  - name: parameter_name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: name of the configuration parameter
    fullyQualifiedName: oracle_test.default.sys.dba_sql_management_config.parameter_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: parameter_value
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    description: value of the configuration parameter
    fullyQualifiedName: oracle_test.default.sys.dba_sql_management_config.parameter_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: last_modified
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp(6)
    description: datetime of last update to the parameter value
    fullyQualifiedName: oracle_test.default.sys.dba_sql_management_config.last_modified
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: modified_by
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: user who last updated the parameter value
    fullyQualifiedName: oracle_test.default.sys.dba_sql_management_config.modified_by
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: a3206ceddb57bbf2cf167ce39583f4fa
processedLineage: false
entityStatus: Approved
