name: int$dba_plsql_object_settings
fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings
tableType: View
columns:
  - name: owner
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.owner
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: object_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.object_id
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: type
    dataType: VARCHAR
    dataLength: 12
    dataTypeDisplay: varchar2(12)
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.type
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: TYPE#
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.TYPE#
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: plsql_optimize_level
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.plsql_optimize_level
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plsql_code_type
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.plsql_code_type
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plsql_debug
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.plsql_debug
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plsql_warnings
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.plsql_warnings
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: nls_length_semantics
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.nls_length_semantics
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plsql_ccflags
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.plsql_ccflags
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plscope_settings
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.plscope_settings
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: sharing
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.sharing
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: origin_con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.int$dba_plsql_object_settings.origin_con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: e0bde3a4197ac88147effae55fea7903
processedLineage: false
entityStatus: Approved
