name: SamlSsoConfig
fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig
description: SAML Single Sign-On Setting
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: SAML Single Sign-On Setting ID
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: IsDeleted
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Deleted
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.IsDeleted
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: DeveloperName
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Name
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.DeveloperName
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: Language
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Master Language
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.Language
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: MasterLabel
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Label
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.MasterLabel
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: NamespacePrefix
    dataType: UNKNOWN
    dataLength: 15
    dataTypeDisplay: string
    description: Namespace Prefix
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.NamespacePrefix
    tags: []
    constraint: "NULL"
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: Version
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: SAML Version
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.Version
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: Issuer
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Issuer
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.Issuer
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: OptionsSpInitBinding
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: SpInitBinding
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.OptionsSpInitBinding
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: OptionsUserProvisioning
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: UserProvisioning
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.OptionsUserProvisioning
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 15
    children: []
    customMetrics: []
  - name: AttributeFormat
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Name ID Format
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.AttributeFormat
    tags: []
    constraint: "NULL"
    ordinalPosition: 16
    children: []
    customMetrics: []
  - name: AttributeName
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Attribute Name
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.AttributeName
    tags: []
    constraint: "NULL"
    ordinalPosition: 17
    children: []
    customMetrics: []
  - name: Audience
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Entity ID
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.Audience
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 18
    children: []
    customMetrics: []
  - name: IdentityMapping
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: SAML Identity Type
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.IdentityMapping
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 19
    children: []
    customMetrics: []
  - name: IdentityLocation
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: SAML Identity Location
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.IdentityLocation
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 20
    children: []
    customMetrics: []
  - name: ExecutionUserId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: User ID
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.ExecutionUserId
    tags: []
    constraint: "NULL"
    ordinalPosition: 21
    children: []
    customMetrics: []
  - name: LoginUrl
    dataType: UNKNOWN
    dataLength: 1500
    dataTypeDisplay: string
    description: Identity Provider Login URL
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.LoginUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 22
    children: []
    customMetrics: []
  - name: LogoutUrl
    dataType: UNKNOWN
    dataLength: 1500
    dataTypeDisplay: string
    description: Identity Provider Logout URL
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.LogoutUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 23
    children: []
    customMetrics: []
  - name: ErrorUrl
    dataType: UNKNOWN
    dataLength: 500
    dataTypeDisplay: string
    description: Custom Error URL
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.ErrorUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 24
    children: []
    customMetrics: []
  - name: ValidationCert
    dataType: UNKNOWN
    dataLength: 4000
    dataTypeDisplay: string
    description: Identity Provider Certificate
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.ValidationCert
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 25
    children: []
    customMetrics: []
  - name: RequestSignatureMethod
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: Request Signature Method
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.RequestSignatureMethod
    tags: []
    constraint: "NULL"
    ordinalPosition: 26
    children: []
    customMetrics: []
  - name: SingleLogoutUrl
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Identity Provider Single Logout URL
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.SingleLogoutUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 27
    children: []
    customMetrics: []
  - name: SingleLogoutBinding
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: Single Logout Request Binding
    fullyQualifiedName: local_salesforce.default.salesforce.SamlSsoConfig.SingleLogoutBinding
    tags: []
    constraint: "NULL"
    ordinalPosition: 28
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 9bda545c-bf37-4c29-b63e-07cabc2b1926
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: local_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: 2cedc857-dacf-4943-b02e-9f2578aaf3c6
  type: database
  name: default
  fullyQualifiedName: local_salesforce.default
  displayName: default
  deleted: false
service:
  id: dd198fe7-cd27-446a-9713-452aa257669c
  type: databaseService
  name: local_salesforce
  fullyQualifiedName: local_salesforce
  displayName: local_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: deleted
      oldValue: false
      newValue: true
  fieldsDeleted: []
  previousVersion: 0.1
sourceUrl: https://energy-fun-7814.my.salesforce.com/lightning/o/SamlSsoConfig/list
domains: []
dataProducts: []
sourceHash: df9d2bd42a4f87d17b8aab7d3641e152
processedLineage: false
entityStatus: Unprocessed
