name: ConnectedApplication
displayName: ""
fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication
description: ""
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Connected App ID
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: Name
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Connected App Name
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.Name
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: OptionsAllowAdminApprovedUsersOnly
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: AllowAdminApprovedUsersOnly
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.OptionsAllowAdminApprovedUsersOnly
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: OptionsRefreshTokenValidityMetric
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: RefreshTokenValidityMetric
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.OptionsRefreshTokenValidityMetric
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: OptionsHasSessionLevelPolicy
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: HasSessionLevelPolicy
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.OptionsHasSessionLevelPolicy
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: OptionsIsInternal
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: isInternal
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.OptionsIsInternal
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: MobileSessionTimeout
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Lock App After
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.MobileSessionTimeout
    tags: []
    constraint: "NULL"
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: PinLength
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: PIN Length
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.PinLength
    tags: []
    constraint: "NULL"
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: StartUrl
    dataType: VARCHAR
    dataLength: 2400
    dataTypeDisplay: url
    description: Start URL
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.StartUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: MobileStartUrl
    dataType: VARCHAR
    dataLength: 2400
    dataTypeDisplay: url
    description: Mobile Start URL
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.MobileStartUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 15
    children: []
    customMetrics: []
  - name: RefreshTokenValidityPeriod
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: int
    description: "Refresh Token Policy:"
    fullyQualifiedName: demo_salesforce.default.salesforce.ConnectedApplication.RefreshTokenValidityPeriod
    tags: []
    constraint: "NULL"
    ordinalPosition: 16
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 577faa78-100e-43dc-87e4-cf005ab3440b
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: demo_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: a01977c7-839c-43d2-833e-0c7d06be0cdc
  type: database
  name: default
  fullyQualifiedName: demo_salesforce.default
  displayName: default
  deleted: false
service:
  id: 57f210f2-9ada-4497-92d4-1ed4316d9dc4
  type: databaseService
  name: demo_salesforce
  fullyQualifiedName: demo_salesforce
  description: ""
  displayName: demo_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: description
      newValue: ""
    - name: displayName
      newValue: ""
    - name: retentionPeriod
      newValue: ""
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary:
    description:
      changedBy: ashish
      changedAt: 1741620822776
retentionPeriod: ""
sourceUrl: https://innovation-force-7398.my.salesforce.com/lightning/o/ConnectedApplication/list
domains: []
dataProducts: []
sourceHash: eff79fe195204c8cd354ff7f8efcd181
processedLineage: false
entityStatus: Approved
