name: DataKitDeploymentLog
displayName: ""
fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog
description: ""
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Data Kit Deployment Log ID
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: OwnerId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Owner ID
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.OwnerId
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: IsDeleted
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Deleted
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.IsDeleted
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: Name
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Name
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.Name
    tags: []
    constraint: "NULL"
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: LastViewedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Viewed Date
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.LastViewedDate
    tags: []
    constraint: "NULL"
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: LastReferencedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Referenced Date
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.LastReferencedDate
    tags: []
    constraint: "NULL"
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: ComponentType
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: Component Type
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.ComponentType
    tags: []
    constraint: "NULL"
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: DeployJob
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: string
    description: Deploy Job
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.DeployJob
    tags: []
    constraint: "NULL"
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: TemplateVersion
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: int
    description: Template Version
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.TemplateVersion
    tags: []
    constraint: "NULL"
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: ComponentName
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: string
    description: Component Name
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.ComponentName
    tags: []
    constraint: "NULL"
    ordinalPosition: 15
    children: []
    customMetrics: []
  - name: DataSpaceName
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: string
    description: Data Space Name
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.DataSpaceName
    tags: []
    constraint: "NULL"
    ordinalPosition: 16
    children: []
    customMetrics: []
  - name: BundleName
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: string
    description: Bundle Name
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.BundleName
    tags: []
    constraint: "NULL"
    ordinalPosition: 17
    children: []
    customMetrics: []
  - name: DataKitName
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: string
    description: Data Kit Name
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.DataKitName
    tags: []
    constraint: "NULL"
    ordinalPosition: 18
    children: []
    customMetrics: []
  - name: DeploymentError
    dataType: VARCHAR
    dataLength: 128000
    dataTypeDisplay: textarea
    description: Deployment Error
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.DeploymentError
    tags: []
    constraint: "NULL"
    ordinalPosition: 19
    children: []
    customMetrics: []
  - name: FlowInterviewIdentifier
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Flow Interview Identifier
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.FlowInterviewIdentifier
    tags: []
    constraint: "NULL"
    ordinalPosition: 20
    children: []
    customMetrics: []
  - name: DeploymentStatus
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: Deployment Status
    fullyQualifiedName: demo_salesforce.default.salesforce.DataKitDeploymentLog.DeploymentStatus
    tags: []
    constraint: "NULL"
    ordinalPosition: 21
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 577faa78-100e-43dc-87e4-cf005ab3440b
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: demo_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: a01977c7-839c-43d2-833e-0c7d06be0cdc
  type: database
  name: default
  fullyQualifiedName: demo_salesforce.default
  displayName: default
  deleted: false
service:
  id: 57f210f2-9ada-4497-92d4-1ed4316d9dc4
  type: databaseService
  name: demo_salesforce
  fullyQualifiedName: demo_salesforce
  description: ""
  displayName: demo_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: description
      newValue: ""
    - name: displayName
      newValue: ""
    - name: retentionPeriod
      newValue: ""
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary:
    description:
      changedBy: ashish
      changedAt: 1741620833902
retentionPeriod: ""
sourceUrl: https://innovation-force-7398.my.salesforce.com/lightning/o/DataKitDeploymentLog/list
domains: []
dataProducts: []
sourceHash: 3717925ac3bc3203bbe79ec41c148662
processedLineage: false
entityStatus: Approved
