name: settings_profiles
fullyQualifiedName: test_clickhouse.default.system.settings_profiles
description: Contains properties of configured setting profiles.
tableType: Regular
columns:
  - name: name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Setting profile name.
    fullyQualifiedName: test_clickhouse.default.system.settings_profiles.name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: id
    dataType: UUID
    dataLength: 1
    dataTypeDisplay: uuid
    description: Setting profile ID.
    fullyQualifiedName: test_clickhouse.default.system.settings_profiles.id
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: storage
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Path to the storage of setting profiles. Configured in the `access_control_path`
      parameter.
    fullyQualifiedName: test_clickhouse.default.system.settings_profiles.storage
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: num_elements
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: uint64
    description: Number of elements for this profile in the `system.settings_profile_elements`
      table.
    fullyQualifiedName: test_clickhouse.default.system.settings_profiles.num_elements
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: apply_to_all
    dataType: SMALLINT
    dataLength: 1
    dataTypeDisplay: uint8
    description: Shows that the settings profile set for all roles and/or users.
    fullyQualifiedName: test_clickhouse.default.system.settings_profiles.apply_to_all
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: apply_to_list
    dataType: ARRAY
    arrayDataType: STRING
    dataTypeDisplay: array<string>
    description: List of the roles and/or users to which the setting profile is applied.
    fullyQualifiedName: test_clickhouse.default.system.settings_profiles.apply_to_list
    tags: []
    children: []
    customMetrics: []
  - name: apply_to_except
    dataType: ARRAY
    arrayDataType: STRING
    dataTypeDisplay: array<string>
    description: The setting profile is applied to all roles and/or users excepting
      of the listed ones.
    fullyQualifiedName: test_clickhouse.default.system.settings_profiles.apply_to_except
    tags: []
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 8a7299bd-4233-40a1-9e70-dc760e5e6b42
  type: databaseSchema
  name: system
  fullyQualifiedName: test_clickhouse.default.system
  displayName: system
  deleted: false
database:
  id: 892667da-43ed-425c-94ad-24a4cc252df4
  type: database
  name: default
  fullyQualifiedName: test_clickhouse.default
  displayName: default
  deleted: false
service:
  id: b468f00e-0925-45e5-a89d-c038e1a5e79f
  type: databaseService
  name: test_clickhouse
  fullyQualifiedName: test_clickhouse
  description: ""
  displayName: test_clickhouse
  deleted: false
serviceType: Clickhouse
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 9267bd4eccba7fc0c56fb4bdfba8ff08
processedLineage: false
entityStatus: Unprocessed
