name: AuthConfigProviders
displayName: ""
fullyQualifiedName: demo_salesforce.default.salesforce.AuthConfigProviders
description: ""
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Auth Config Provider ID
    fullyQualifiedName: demo_salesforce.default.salesforce.AuthConfigProviders.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: IsDeleted
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Deleted
    fullyQualifiedName: demo_salesforce.default.salesforce.AuthConfigProviders.IsDeleted
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: demo_salesforce.default.salesforce.AuthConfigProviders.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.AuthConfigProviders.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: demo_salesforce.default.salesforce.AuthConfigProviders.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.AuthConfigProviders.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: demo_salesforce.default.salesforce.AuthConfigProviders.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: AuthConfigId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Authentication Configuration ID
    fullyQualifiedName: demo_salesforce.default.salesforce.AuthConfigProviders.AuthConfigId
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: AuthProviderId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Authentication Provider ID
    fullyQualifiedName: demo_salesforce.default.salesforce.AuthConfigProviders.AuthProviderId
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 577faa78-100e-43dc-87e4-cf005ab3440b
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: demo_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: a01977c7-839c-43d2-833e-0c7d06be0cdc
  type: database
  name: default
  fullyQualifiedName: demo_salesforce.default
  displayName: default
  deleted: false
service:
  id: 57f210f2-9ada-4497-92d4-1ed4316d9dc4
  type: databaseService
  name: demo_salesforce
  fullyQualifiedName: demo_salesforce
  description: ""
  displayName: demo_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: description
      newValue: ""
    - name: displayName
      newValue: ""
    - name: retentionPeriod
      newValue: ""
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary:
    description:
      changedBy: ashish
      changedAt: 1741620815039
retentionPeriod: ""
sourceUrl: https://innovation-force-7398.my.salesforce.com/lightning/o/AuthConfigProviders/list
domains: []
dataProducts: []
sourceHash: 00e9493aebcc404ba98898257207d183
processedLineage: false
entityStatus: Approved
