name: AuthConfigProviders
fullyQualifiedName: local_salesforce.default.salesforce.AuthConfigProviders
description: Authentication Configuration Auth. Provider
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Auth Config Provider ID
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfigProviders.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: IsDeleted
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Deleted
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfigProviders.IsDeleted
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfigProviders.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfigProviders.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfigProviders.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfigProviders.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfigProviders.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: AuthConfigId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Authentication Configuration ID
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfigProviders.AuthConfigId
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: AuthProviderId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Authentication Provider ID
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfigProviders.AuthProviderId
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 9bda545c-bf37-4c29-b63e-07cabc2b1926
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: local_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: 2cedc857-dacf-4943-b02e-9f2578aaf3c6
  type: database
  name: default
  fullyQualifiedName: local_salesforce.default
  displayName: default
  deleted: false
service:
  id: dd198fe7-cd27-446a-9713-452aa257669c
  type: databaseService
  name: local_salesforce
  fullyQualifiedName: local_salesforce
  displayName: local_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: deleted
      oldValue: false
      newValue: true
  fieldsDeleted: []
  previousVersion: 0.1
sourceUrl: https://energy-fun-7814.my.salesforce.com/lightning/o/AuthConfigProviders/list
domains: []
dataProducts: []
sourceHash: 6fec00be411deca3e5eadf35c3982ec5
processedLineage: false
entityStatus: Unprocessed
