name: AuthConfig
fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig
description: Authentication Configuration
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Authentication Configuration ID
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: IsDeleted
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Deleted
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.IsDeleted
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: DeveloperName
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Name
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.DeveloperName
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: Language
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Master Language
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.Language
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: MasterLabel
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Label
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.MasterLabel
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: NamespacePrefix
    dataType: UNKNOWN
    dataLength: 15
    dataTypeDisplay: string
    description: Namespace Prefix
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.NamespacePrefix
    tags: []
    constraint: "NULL"
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: Url
    dataType: UNKNOWN
    dataLength: 240
    dataTypeDisplay: string
    description: URL
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.Url
    tags: []
    constraint: UNIQUE
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: AuthOptionsUsernamePassword
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: UsernamePassword
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.AuthOptionsUsernamePassword
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: AuthOptionsSaml
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Saml
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.AuthOptionsSaml
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: AuthOptionsAuthProvider
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: AuthProvider
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.AuthOptionsAuthProvider
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 15
    children: []
    customMetrics: []
  - name: IsActive
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Is Active
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.IsActive
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 16
    children: []
    customMetrics: []
  - name: Type
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: Authentication Configuration Type
    fullyQualifiedName: local_salesforce.default.salesforce.AuthConfig.Type
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 17
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 9bda545c-bf37-4c29-b63e-07cabc2b1926
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: local_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: 2cedc857-dacf-4943-b02e-9f2578aaf3c6
  type: database
  name: default
  fullyQualifiedName: local_salesforce.default
  displayName: default
  deleted: false
service:
  id: dd198fe7-cd27-446a-9713-452aa257669c
  type: databaseService
  name: local_salesforce
  fullyQualifiedName: local_salesforce
  displayName: local_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: deleted
      oldValue: false
      newValue: true
  fieldsDeleted: []
  previousVersion: 0.1
sourceUrl: https://energy-fun-7814.my.salesforce.com/lightning/o/AuthConfig/list
domains: []
dataProducts: []
sourceHash: 24872e6e12f3e6768facb494db07c0d9
processedLineage: false
entityStatus: Unprocessed
