name: ConnectedApplication
fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication
description: Connected App
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Connected App ID
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: Name
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Connected App Name
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.Name
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: OptionsAllowAdminApprovedUsersOnly
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: AllowAdminApprovedUsersOnly
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.OptionsAllowAdminApprovedUsersOnly
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: OptionsRefreshTokenValidityMetric
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: RefreshTokenValidityMetric
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.OptionsRefreshTokenValidityMetric
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: OptionsHasSessionLevelPolicy
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: HasSessionLevelPolicy
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.OptionsHasSessionLevelPolicy
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: OptionsIsInternal
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: isInternal
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.OptionsIsInternal
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: MobileSessionTimeout
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Lock App After
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.MobileSessionTimeout
    tags: []
    constraint: "NULL"
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: PinLength
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: PIN Length
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.PinLength
    tags: []
    constraint: "NULL"
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: StartUrl
    dataType: VARCHAR
    dataLength: 2400
    dataTypeDisplay: url
    description: Start URL
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.StartUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: MobileStartUrl
    dataType: VARCHAR
    dataLength: 2400
    dataTypeDisplay: url
    description: Mobile Start URL
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.MobileStartUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 15
    children: []
    customMetrics: []
  - name: RefreshTokenValidityPeriod
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: int
    description: "Refresh Token Policy:"
    fullyQualifiedName: local_salesforce.default.salesforce.ConnectedApplication.RefreshTokenValidityPeriod
    tags: []
    constraint: "NULL"
    ordinalPosition: 16
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 9bda545c-bf37-4c29-b63e-07cabc2b1926
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: local_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: 2cedc857-dacf-4943-b02e-9f2578aaf3c6
  type: database
  name: default
  fullyQualifiedName: local_salesforce.default
  displayName: default
  deleted: false
service:
  id: dd198fe7-cd27-446a-9713-452aa257669c
  type: databaseService
  name: local_salesforce
  fullyQualifiedName: local_salesforce
  displayName: local_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: deleted
      oldValue: false
      newValue: true
  fieldsDeleted: []
  previousVersion: 0.1
sourceUrl: https://energy-fun-7814.my.salesforce.com/lightning/o/ConnectedApplication/list
domains: []
dataProducts: []
sourceHash: 8cf5b54bdbddb90f683fbcb2df408a3b
processedLineage: false
entityStatus: Unprocessed
