name: openmetadata_settings
fullyQualifiedName: local_mysql.default.openmetadata_db.openmetadata_settings
tableType: Regular
columns:
  - name: id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: mediumint
    fullyQualifiedName: local_mysql.default.openmetadata_db.openmetadata_settings.id
    tags: []
    children: []
    customMetrics: []
  - name: configType
    dataType: VARCHAR
    dataLength: 36
    dataTypeDisplay: varchar(36)
    fullyQualifiedName: local_mysql.default.openmetadata_db.openmetadata_settings.configType
    tags: []
    children: []
    customMetrics: []
  - name: json
    dataType: JSON
    dataLength: 1
    dataTypeDisplay: json
    fullyQualifiedName: local_mysql.default.openmetadata_db.openmetadata_settings.json
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints:
  - constraintType: PRIMARY_KEY
    columns:
      - id
      - configType
owners: []
databaseSchema:
  id: a122ff6b-96c2-4226-9538-7bcc9533a029
  type: databaseSchema
  name: openmetadata_db
  fullyQualifiedName: local_mysql.default.openmetadata_db
  displayName: openmetadata_db
  deleted: false
database:
  id: bc11e171-762a-4933-9a5d-56ad1440c4bd
  type: database
  name: default
  fullyQualifiedName: local_mysql.default
  displayName: default
  deleted: false
service:
  id: 4e6c8a97-187c-4b33-88a3-353dccaa316c
  type: databaseService
  name: local_mysql
  fullyQualifiedName: local_mysql
  description: <p>data testing</p>
  displayName: local_mysql
  deleted: false
serviceType: Mysql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 837e079624ae5269ae5ef8e27ee399c6
processedLineage: false
entityStatus: Approved
